# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w2mlils4vM9SQndHfneqEj-zw2gucIey
"""

from sklearn import datasets
import random
import math
import numpy as np
iris = datasets.load_iris()
x= iris.data[:, :2]

def dist(x,y):
  return math.sqrt((x[0]-x[1])**2 + (y[0]-y[1])**2)

print(math.dist([0,0], [5,5]))
print(math.sqrt(50))

#K=2
def KMeans(x):
  c1 = [random.randint(0,8), random.randint(0,5)]
  c2 = [random.randint(0,8), random.randint(0,5)]
  cluster1 = []
  cluster2 = []
  xAvg1=0
  xAvg2=0
  yAvg1=0
  yAvg2=0
  n = len(x)
  diff1 = 1
  diff2 = 1
  while diff1 > 0.1 and diff2 > 0.1:
    for i in range(n):
      cluster1.append(x[i]) if min(math.dist(x[i], c1), math.dist(x[i], c2)) == math.dist(x[i], c1) else cluster2.append(x[i])
    tempC1 = c1
    tempC2 = c2
    #print("Clust 1:", cluster1)
    for i in range(len(cluster1)):
      xAvg1 = xAvg1 + cluster1[i][0]
      yAvg1 = yAvg1 + cluster1[i][1]
    for i in range(len(cluster2)):
      xAvg2 = xAvg2 + cluster2[i][0]
      yAvg2 = yAvg2 + cluster2[i][1]
    if len(cluster1) !=0:
      xAvg1 = xAvg1/len(cluster1)
      yAvg1 = yAvg1/len(cluster1)
    if len(cluster2) !=0:  
      xAvg2 = xAvg2/len(cluster2)
      yAvg2 = yAvg2/len(cluster2)
    c1 = [xAvg1,yAvg1]
    c2 = [xAvg2,yAvg2]
    diff1 = dist(tempC1, c1)
    diff2 = dist(tempC2, c2)
    print("dif1,dif2: ", [diff1,diff2])
    #print("temp c1,c2 :",[tempC1, tempC2]) 
    print("c1,c2 :",[c1,c2]) 
  return [c1,c2]

print(KMeans(x))

print(x)